#!/bin/sh

# rmake [build_type [build_shared_libs]]
# default: rmake Debug False
# examples:
# rmake
# rmake Debug
# rmake Release
# rmake Debug True

BUILD_TYPE=$1
if [ "$BUILD_TYPE" = "" ]
then
  BUILD_TYPE=Debug
fi

BUILD_SHARED_LIBS=$2
if [ "$BUILD_SHARED_LIBS" = "" ]
then
  BUILD_SHARED_LIBS=False
fi

if [ $BUILD_TYPE != Debug -a $BUILD_TYPE != Release ]
then
  echo "Invalid build configuration \"$BUILD_TYPE\". Please specify Debug or Release."
  exit 1
fi

if [ $BUILD_SHARED_LIBS != True -a $BUILD_SHARED_LIBS != False ]
then
  echo "Invalid value for BUILD_SHARED_LIBS \"$BUILD_SHARED_LIBS\". Please specify True or False."
  exit 1
fi

echo "rmake configuration:"
echo " BUILD_TYPE        $BUILD_TYPE"
echo " BUILD_SHARED_LIBS $BUILD_SHARED_LIBS"
echo

if [ ! -f "./build" ]; then mkdir build 2>/dev/null; fi

cd build
if [ ! -f "./$BUILD_TYPE" ]; then mkdir "./$BUILD_TYPE" 2>/dev/null; fi

cd $BUILD_TYPE

conan install ../../conanfile.py --options "*:shared=$BUILD_SHARED_LIBS"
cmake ../.. -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSKIP_INSTALL_ALL=true -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS
# 8 threads available for parallel building
cmake --build . -- -j8
if [ $? != 0 ]
then
  echo 'Build failed. Not running unit tests.'
  exit 1
fi

ctest -C $BUILD_TYPE
if [ $? != 0 ]
then
  echo 'Unit tests failed.'
  exit 1
fi

# Install into the Conan cache
conan create ../.. branch/testing \
  --json conan-install.json \
  --build outdated \
  --options "*:shared=$BUILD_SHARED_LIBS" \
  --options "BranchIO:source_folder=`pwd`/../.." \
  --settings build_type=$BUILD_TYPE
if [ $? != 0 ]
then
  echo 'conan create failed.'
  exit 1
fi

echo "Building stage from conan cache"
../../BranchSDK/tools/stage.py
if [ $? != 0 ]
then
  echo 'stage.py failed.'
  exit 1
fi

cd ../..

# Lint
pushd .
cd BranchSDK/src
../tools/cpplint.py --linelength=120 --filter=-build/namespaces,-runtime/references --recursive --repository=. ./BranchIO/*.*
if [ $? != 0 ]
then
  echo 'Linting failed.'
  exit 1
fi
popd

# build docs
cd BranchSDK
doxygen
cd ..
