"""
Script to build Product.wxs for Wix installer using the output
of stage.py under build\*\stage.
"""

# TODO: Don't necessarily need ET here, since we're just generating
# text, but this may be more flexible.

import json, os, shutil
from xml.dom import minidom
import xml.etree.ElementTree as ET
from xml.etree.ElementTree import Comment, Element, SubElement

# -----
# ----- Utilities used below
# -----

# https://pymotw.com/2/xml/etree/ElementTree/create.html
def prettify(elem):
    """Return a pretty-printed XML string for the Element.
    """
    rough_string = ET.tostring(elem, 'utf-8')
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ")

def make_directory_elem(elem, identifier, name=None):
    if name:
        return SubElement(elem, "Directory", {"Id": identifier, "Name": name})
    else:
        return SubElement(elem, "Directory", {"Id": identifier})

def folder_name(path):
    split_path = os.path.splitdrive(path)
    path_components = split_path[1].split(os.sep)
    name = ""

    ignoring = True
    for component in path_components:
        if component == "include":
            ignoring = False

        if ignoring:
            continue

        name = name + component.upper()

    return name + "FOLDER"

"""
Produces a nested tree of Directory elements like:

          <Directory Id="INCLUDEFOLDER" Name="include">
            <Directory Id="BRANCHIOINCLUDEFOLDER" Name="BranchIO">
              <Directory Id="BRANCHIOEVENTINCLUDEFOLDER" Name="Event" />
            </Directory>
          </Directory>
"""
def wix_directory(elem, path):
    basepath = os.path.basename(path)
    directory_id = folder_name(path)
    wdir = make_directory_elem(elem, directory_id, basepath)

    files = os.listdir(path)
    for f in files:
        full_path = os.path.join(path, f)
        if not os.path.isdir(full_path):
            continue
        wix_directory(wdir, full_path)

    return wdir

# -----
# ----- General header elements
# -----

root = Element("Wix", {"xmlns": "http://schemas.microsoft.com/wix/2006/wi"})
root.append(Comment(" Generated by build_wix.py. Do not edit by hand. "))
product = SubElement(root, "Product", {
    "Id": "*",
    "Name": "Branch C++ SDK for Windows",
    "Language": "1033",
    "Version": "0.1.0",
    "Manufacturer": "Branch Metrics, Inc.",
    "UpgradeCode": "29b1dc08-2190-48f0-bc3c-7455381f2156"
    })
SubElement(product, "Package", {
    "InstallerVersion": "200",
    "Compressed": "yes",
    "InstallScope": "perMachine"
    })
SubElement(product, "MajorUpgrade", {
    "DowngradeErrorMessage": "A newer version of [ProductName] is already installed."
    })
SubElement(product, "Media", {
    "Id": "1",
    "Cabinet": "cab1.cab",
    "EmbedCab": "yes"
    })
SubElement(product, "Icon", {
    "Id": "branch.ico",
    "SourceFile": "branch-badge-dark.ico"
    })
SubElement(product, "Property", {
    "Id": "ARPPRODUCTION",
    "Value": "branch.ico"
    })

feature = SubElement(product, "Feature", {
    "Id": "ProductFeature",
    "Title": "Branch Installer",
    "Level": "1"
    })

# -----
# ----- ComponentGroups to be included (defined below)
# -----

SubElement(feature, "ComponentGroupRef", {"Id": "BranchHeaders"})
SubElement(feature, "ComponentGroupRef", {"Id": "BranchLibrariesX64"})
SubElement(feature, "ComponentGroupRef", {"Id": "BranchLibrariesX86"})
SubElement(feature, "ComponentGroupRef", {"Id": "ThirdPartyHeaders"})
SubElement(feature, "ComponentGroupRef", {"Id": "ThirdPartyLibrariesX64"})
SubElement(feature, "ComponentGroupRef", {"Id": "ThirdPartyLibrariesX86"})

# os.path.abspath & os.path.join build the right kind of path for the os,
# using backslashes on Windows without typing \\ every time here.
build_root = os.path.abspath(os.path.dirname(__file__) + "../../build")

# Take all header files from Releasex64 arbitrarily, since they
# don't vary by build.
stage_root = os.path.join(build_root, "Releasex64", "stage")
include_root = os.path.join(stage_root, "include")
lib_root = os.path.join(stage_root, "lib")

# -----
# ----- Directory tree Fragment.
# ----- Defines directories to be populated on install.
# -----

dir_fragment = SubElement(root, "Fragment")
source_dir = make_directory_elem(dir_fragment, "TARGETDIR", "SourceDir")
# C:\Program Files (x86)
program_files_folder = make_directory_elem(source_dir, "ProgramFilesDir")
# C:\Program Files (x86)\Branch SDK
branch_sdk_install_folder = make_directory_elem(program_files_folder, "INSTALLFOLDER", "Branch SDK")

# Recursively build a nested tree of Directory elements to describe
# all header folders to be installed.
wix_directory(branch_sdk_install_folder, include_root)

lib_folder = make_directory_elem(branch_sdk_install_folder, "LIBFOLDER", "lib")
x64_lib_folder = make_directory_elem(lib_folder, "X64LIBFOLDER", "x64")
x86_lib_folder = make_directory_elem(lib_folder, "X86LIBFOLDER", "x86")
x64_debug_folder = make_directory_elem(x64_lib_folder, "X64DEBUGLIBFOLDER", "Debug")
x86_debug_folder = make_directory_elem(x86_lib_folder, "X86DEBUGLIBFOLDER", "Debug")
x64_release_folder = make_directory_elem(x64_lib_folder, "X64RELEASELIBFOLDER", "release")
x86_release_folder = make_directory_elem(x86_lib_folder, "X86RELEASELIBFOLDER", "release")

# -----
# ----- ComponentGroup list Fragment
# ----- Defines individual files to be installed.
# -----
cg_fragment = SubElement(root, "Fragment")
branch_headers = SubElement(cg_fragment, "ComponentGroup", {"Id": "BranchHeaders"})
branch_libraries_x64 = SubElement(cg_fragment, "ComponentGroup", {"Id": "BranchLibrariesX64"})
branch_libraries_x86 = SubElement(cg_fragment, "ComponentGroup", {"Id": "BranchLibrariesX86"})
third_party_headers = SubElement(cg_fragment, "ComponentGroup", {"Id": "ThirdPartyHeaders"})
third_party_libraries_x64 = SubElement(cg_fragment, "ComponentGroup", {"Id": "ThirdPartyLibrariesX64"})
third_party_libraries_x86 = SubElement(cg_fragment, "ComponentGroup", {"Id": "ThirdPartyLibrariesX86"})

# -----
# ----- Generate output
# -----

output = prettify(root)
print(output)

output_path = os.path.abspath(build_root + "/../BranchSDK/Windows/BranchInstaller/Product.wxs")
open(output_path, "w").write(output)
