#! /usr/bin/env python

import json, os, shutil
from os import makedirs

# Recursively copy src directory into dst directory
# excludes is a list of patterns to exclude
def copyall(src, dst, excludes=[]):
    # ignores is a function to be passed to copytree
    ignores = shutil.ignore_patterns(*excludes)
    all_files = os.listdir(src)
    # rejects is a set of all files matching the excludes
    rejected = ignores(src, all_files)
    files = [f for f in all_files if f not in rejected]

    for f in files:
        path = src + "/" + f
        if os.path.isdir(path) and os.path.exists(dst + "/" +f):
            # copytree fails if the destination directory already exists.
            # That's the purpose of this function. Call it recursively in
            # this case.
            copyall(path, dst + "/" +f, excludes=excludes)
        elif os.path.isdir(path):
            shutil.copytree(path, dst + "/" + f, ignore=ignores)
        else:
            shutil.copy(path, dst)

# Generated by conan create
f = open("conan-install.json", "r")
install_data = json.loads(f.read())

installed = install_data["installed"]

# Copy everything under stage (e.g. build\Debugx64\stage)

# Always start fresh
shutil.rmtree("stage", ignore_errors=True)
makedirs("stage/include")
makedirs("stage/lib")

# Skip Poco's MongoDB and SQLiteData modules, which we don't require.
# Also CppUnit, which one of our deps uses.
excludes = ["CppUnit", "*MongoDB*", "*DataSQLite*"]

for item in installed:
    recipe = item["recipe"]
    print(recipe["id"])

    package_name = recipe["name"]

    for package in item["packages"]:
        rootpath = package["cpp_info"]["rootpath"]
        print(" " + rootpath + " -> stage")

        copyall(rootpath + "/include", "stage/include", excludes=excludes)
        copyall(rootpath + "/lib", "stage/lib", excludes=excludes)
