name: rmake.bat

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Inspect workspace
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: Get-Location

      - uses: actions/checkout@v2

      - name: Show workspace contents
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: Get-ChildItem

      - name: Install cmake and conan
        run: pip install --user cmake conan

      - name: Build Debug
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts"; .\rmake.bat Debug

      - name: Build Release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts"; .\rmake.bat Release
