name: rmake.bat

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Inspect workspace
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: Get-Location; dir

      - name: Install cmake and conan
        run: pip install --user cmake conan

      - name: Build Debug
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: rmake.bat Debug

      - name: Build Release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: rmake.bat Release
