name: rmake.bat

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cmake and conan
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: pip install --user -r requirements.txt

      - name: Restore Conan cache, profiles, settings
        uses: actions/cache@v2
        with:
          path: ~/.conan
          key: ${{ runner.os }}-${{ hashFiles('locks') }}

      # Note this is stored in ~/.conan and will be imported with the cache. This profile new command can fail.
      - name: Set up default conan profile
        continue-on-error: true
        run: C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts\conan profile new default --detect

      - name: 64-bit Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          .\ci.bat 64

      - name: 32-bit Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          .\ci.bat 32
