name: rmake.bat

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install cmake and conan
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: pip install --user -r requirements.txt

      - name: Set up default conan profile
        run: C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts\conan profile new default --detect

      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          .\ci.bat
