name: rmake.bat

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Inspect workspace
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: Get-Location

      - name: Show workspace contents
        run: Get-ChildItem -Path ${{env.GITHUB_WORKSPACE}}

      - name: Install cmake and conan
        run: pip install --user cmake conan

      - name: Build Debug
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ${{env.GITHUB_WORKSPACE}}\rmake.bat Debug

      - name: Build Release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ${{env.GITHUB_WORKSPACE}}\rmake.bat Release
