name: rmake.bat

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install cmake and conan
        run: pip install --user cmake conan

      - name: Build Debug
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: .\rmake Debug

      - name: Build Release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: .\rmake Release
