name: rmake.bat

on: [push]

jobs:
  build:
    runs-on: windows-latest

    env:
      VSINSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community

    steps:
      - uses: actions/checkout@v2

      - name: Install cmake and conan
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: pip install --user -r requirements.txt

      - name: Set up default conan profile
        run: C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts\conan profile new default --detect

      - name: Build Debug
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts;${{ env.VSINSTALLDIR }}\VC\Auxiliary\Build" |
          C:vcvars64.bat
          .\rmake.bat Debug

      - name: Build Release
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          $env:Path += ";C:\Users\runneradmin\AppData\Roaming\Python\Python37\Scripts;${{ env.VSINSTALLDIR }}\VC\Auxiliary\Build" |
          C:vcvars64.bat
          .\rmake.bat Release
